LED Pulse Lead, Inversion, and Number of Pulses support (#48)
* use the latest version of libmultisense

* add led pulse width and inversion support

* Set external transform on camera (#52)

* update libmultisense to latest

* Add a URDF for the KS21 (#57)

* Importable xacro fixes to remove duplicate root frames and fix typos (#61)

* Importable xacro fixes to remove duplicate root frames and fix typos

* Remove importable xacro files which are not used by multisense_ros

* fix: added robot_state_publisher to multisense_bringup deps (#63)

Launch file validation requires all included packages to be dependencies

* feat: Made remote heads required nodes (#64)

* Add a S30 URDF (#62)

* Update exposure limits for nex-gen cameras (#65)

* Update the LibMultiSense submodule (#66)

* Add Remote Head Support (#44)

* initial remote head support, mostly reconfigure updates

* clean up reconfigure for mono cameras and remote head

* reorganize the topic publishing so stereo and color topics are not advertised if the camera cannot support them

* add a launch file for remote head and update urdf with first pass but incorrect remote head support

* fix the urdf issues on launch caused by incorrect file paths and names

* fix logical error in reconfigure that caused all remote heads to behave like a vpb

* update launch files after debugging

* update to latest libmultisense version

* Update multisense_ros/cfg/multisense.cfg

Co-authored-by: David Robinson <drobinson@carnegierobotics.com>

* update default head ID in the ros driver

* Add grayscale support for pointcloud colorization

* account for the possibility of an uninitialized stereo calibration manager

* update the valid gain range for AR0234 imagers

* fix typo in config

* make camera.cpp robust for cameras with no right imager

* Fix stereo_calibration_manager logic check

* fix: changed standard to c++17 because of std::shared_mutex (#49)

* fix: changed standard to c++17 because of std::shared_mutex

```
In file included from /usr/include/log4cxx/log4cxx.h:45,
                 from /usr/include/log4cxx/logstring.h:28,
                 from /usr/include/log4cxx/level.h:22,
                 from /usr/include/ros/console.h:46,
                 from /usr/include/ros/ros.h:40,
                 from /home/fpasqualini/work/minibot/catkin_ws/src/minibot_meta/multisense_ros/multisense_ros/include/multisense_ros/color_laser.h:41,
                 from /home/fpasqualini/work/minibot/catkin_ws/src/minibot_meta/multisense_ros/multisense_ros/src/color_laser.cpp:36:
/usr/include/log4cxx/boost-std-configuration.h:10:18: error: ‘shared_mutex’ in namespace ‘std’ does not name a type
   10 |     typedef std::shared_mutex shared_mutex;
      |                  ^~~~~~~~~~~~
/usr/include/log4cxx/boost-std-configuration.h:10:13: note: ‘std::shared_mutex’ is only available from C++17 onwards
   10 |     typedef std::shared_mutex shared_mutex;
      |             ^~~
```

Multiple errors like this appear when using GCC 11 and C++ 14

* Update CMakeLists.txt

* update libmultisenes version

* Update min gain params

---------

Co-authored-by: David Robinson <drobinson@carnegierobotics.com>
Co-authored-by: Matt Alvarado <malvarado@carnegierobotics.com>
Co-authored-by: Frank Pasqualini <pasqualinifrank@gmail.com>

---------

Co-authored-by: David Robinson <drobinson@carnegierobotics.com>
Co-authored-by: Matt Alvarado <malvarado@carnegierobotics.com>
Co-authored-by: Frank Pasqualini <pasqualinifrank@gmail.com>